name: Python CI

on:
  push:
    branches: [ main, task-1, task-2, task-3 ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: pip install -r requirements.txt
      - run: python -m textblob.download_corpora
      - run: pytest tests/ -v --tb=short